### ISSUE TITLE
Exception has occurred: AttributeError module 'RedDownloader' has no attribute 'DownloadVideosBySubreddit'

### ISSUE THREAD

**Issue by codingeologist** [Jackhammer9/RedDownloader#44]
Version 4.2.0:

Reddit API methods are missing:

RedDownloader.DownloadBySubreddit
RedDownloader.DownloadImagesBySubreddit
RedDownloader.DownloadVideosBySubreddit
RedDownloader.DownloadGalleriesBySubreddit

**Comment by Jackhammer9** [comment]
Checked all methods and everything is fine the issue can't be reproduced.

Code Executed:

```python
from RedDownloader import RedDownloader

RedDownloader.DownloadBySubreddit("memes" , 1)
RedDownloader.DownloadGalleriesBySubreddit("blender", 1)
RedDownloader.DownloadImagesBySubreddit("unity2d",1)
RedDownloader.DownloadVideosBySubreddit("videos",1)
```

**Comment by codingeologist** [comment]
Which version is this on?

**Comment by Jackhammer9** [comment]
Greetings you should be able to access these methods from the latest releases of RedDownloader at the time of writing this the latest version is [4.2.0](https://pypi.org/project/RedDownloader/)

**Comment by Jackhammer9** [comment]
Stale Issue No New Comments
