### ISSUE TITLE
It just stops working

### ISSUE THREAD

**Issue by skintflickz** [Jackhammer9/RedDownloader#46]
worked fine for about 8 times then would not work at all.
Plus the more I used it the slower it ran ?
Checked task manager and it wasn't killin the cpu or memory.

**Comment by skintflickz** [comment]
I think its the API, if I wait for 20 mins it works fine again for another 4 -5 scrapes.
Perhaps add proxy support ?

**Comment by skintflickz** [comment]
FYI

INFO: Fetching Posts...
INFO: Unable to fetch posts
INFO: HTTPSConnectionPool(host='jackhammer.pythonanywhere.com', port=443): Max retries exceeded with url: //reddit/subreddit/all?subreddit=memes&number=15&sort=hot (Caused by SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1129)')))

**Comment by Jackhammer9** [comment]
Greetings,

I just checked through and was not able to replicate the issue. I ran a while loop to download certain gallery posts and it kept downloading as you expected. I manually stopped it after about 16 downloads the double of what you were stating.

The time for each iteration of download was also constant.

Can you please share the code snippet you were trying to run or try again and mention if the problem persists?

**Comment by Jackhammer9** [comment]
Stale Issue
