### ISSUE TITLE
It isn't downloading v.redd.it & i.redd.it submissions

### ISSUE THREAD

**Issue by tribhuwan-kumar** [Jackhammer9/RedDownloader#51]
## code:
```
from RedDownloader import RedDownloader
RedDownloader.Download("https://i.redd.it/pjejgqxwnmyb1.jpg")
```
## Error:
`INFO: Error: Could Not Recognize Post Type`

### But it downloads the same post from different link

**Comment by Jackhammer9** [comment]
Greetings @tribhuwan-kumar ,

Thank you for your issue as per your request RedDownloader will now support downloading files directly from i.redd.it and v.reddit urls. These changes would reflect in the next version of RedDownloader so please kindly update to it when the next version rolls out

Jackhammer
