### ISSUE TITLE
Video has no sound 

### ISSUE THREAD

**Issue by promiseer** [Jackhammer9/RedDownloader#52]
I have tried downloading several posts from Reddit, but every video downloaded does not have sound.
![image](https://github.com/Jackhammer9/RedDownloader/assets/77802905/fd64ba96-9e0f-4f10-8abd-552b551ca9bd)

**Comment by Gianpi612** [comment]
Same issue, when downloading files from reddit the video has no sound

**Comment by Jackhammer9** [comment]
Greetings,

The issue has been fixed with the help of @farukucgun and would be released in the new version of RedDownloader. Thank you for your issue
